version: '3.9'

services:
    db:
      image: rojesh.azurecr.io/db:latest
      ports:
        - "27017:27017"
      restart: always
      networks:
        - app-network

    server:
      image: rojesh.azurecr.io/server:latest
      depends_on:
        - db
      ports:
        - "3000:3000"
      restart: always
      networks:
        - app-network

    app:
      depends_on:
        - server
      image: rojesh.azurecr.io/app:latest
      environment:
        NGINX_HOST: rojesh.azurewebsites.net
        NGINX_PORT: 80
      ports:
        - "80:80"
      restart: always
      networks:
        - app-network

networks:
  app-network:
    driver: bridge   
      