version: '3.9'

services:
  nginx-app:
    build:
      context: app #name of app
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - app-network  

  node-server:
    build:
      context: server
      dockerfile: Dockerfile
    # restart: always
    # environment: 
    #   PORT: 3000
    #   MONGODB_URI: mongodb://mongo:27017/rojesh
    #   JWT_SECRET: mysupersecretkey
    ports:
      - 3000:3000
    depends_on: 
      - mongo-db
    volumes:
      - ./server:/server
    # environment: 
    #   - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/rojesh
    networks:
      - app-network  

  mongo-db:
    container_name: mongo-server
    image: mongo:latest
    ports:
      - 27017:27017
    # restart: always
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge
    


