version: '3.9'

services:
  docker-app:
    build:
      context: app #name of app
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - ./app/src:/app/src 
      # map both directory local and container

  docker-server:
    build:
      context: server
      dockerfile: Dockerfile
    # restart: always
    environment: 
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/rojesh
      JWT_SECRET: mysupersecretkey
    ports:
      - 3000:3000
    depends_on: 
      - mongo
    volumes:
      - ./server:/server
    # environment: 
    #   - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/rojesh

  mongo:
    container_name: mongo-server
    image: mongo:latest
    ports:
      - 27017:27017
    # restart: always
    


